const ApiCodes = {
	// common
	300: "Thành công",
	301: "Thất bại",
	302: "Tạo thành công",
	303: "Cập nhật thành công",
	304: "Xóa thành công",
	305: "Cập nhật trạng thái thành công",
	306: "Tạo thất bại",
	307: "Cập nhật thất bại",
	308: "Xóa thất bại",
	309: "Cập nhật trạng thái thất bại",
	// User
	1: "Số điện thoại không hợp lệ!",
	2: "Email không hợp lệ!",
	3: "Số điện thoại này đã được đăng ký!",
	4: "Email đã tồn tạii!",
	5: "Người dùng không trong độ tuổi lao động!",
	7: "Sai mật khẩu!",
	8: "Tài khoản đã bị khoá!",
	9: "Không tìm thấy số điện thoại!",
	10: "Không tìm thấy thông tin người dùng!",
	11: "Không tìm thấy thông tin vai trò người dùng!",
	12: "Không tìm thấy thông tin UserRole!",
	94: "Hãy xoá hết người dùng trước khi xoá tổ",
	95: "Công nhân đang ở tổ khác, hãy xoá ra khỏi trước khi thêm vào tổ mới!",
	96: "Tổ đã có tổ trưởng!",
	78: "Công nhân đang thực hiện công việc, hiện tại không thể khoá tài khoản!",
	79: "Tổ trưởng đang thực hiện công việc, hiện tại không thể khoá tài khoản!",
	80: "Quản đốc đang thực hiện đơn hàng, hiện tại không thể khoá tài khoản!",
	81: "Công nhân đang thực hiện công việc, hiện tại không thay đổi vai trò!",
	83: "Tổ trưởng đang thực hiện công việc, hiện tại không thay đổi vai trò!",
	84: "Quản đốc đang thực hiện đơn hàng, hiện tại không thể thay đổi vai trò!",
	85: "Không thể thay đổi vai trò của quản trị viên!",
	102: "Tổ trưởng đang ở tổ khác!",
	//Group
	16: "Tên tổ đã tồn tại!",
	17: "Hãy xoá công nhân khỏi nhóm trước khi thêm vào tổ mới!",
	18: "Không tìm thấy người dùng trong hệ thống!",
	19: "Hãy xoá người dùng ra khỏi nhóm!",
	20: "Không tìm thấy tổ trưởng trong hệ thống!",
	21: "Người dùng không phải tổ trưởng!",
	22: "Người dùng không phải công nhân!",
	//MaterialCategory
	24: "Tên loại vật liệu này đã tồn tại!",
	25: "Không tìm thấy thông tin loại vật liệu!",
	26: "Hãy xoá hết vật liệu trước khi xoá loại vật liệu!",
	//Material
	27: "Tên vật liệu này đã tồn tại!",
	28: "Không tìm thấy thông tin loại vật liệu!",
	29: "Không tìm thấy thông tin vật liệu!",
	97: "Không tìm thấy thông tin đơn hàng!",
	82: "Vật liệu này đang tồn tại trong sản phẩm, hãy xoá ra khỏi sản phẩm trước khi xoá vật liệu!",
	//ItemCategory
	30: "Tên loại mặt hàng này đã tồn tại!",
	31: "Không tìm thấy thông tin loại mặt hàng!",
	32: "Hãy xoá hết mặt hàng trước khi xoá loại mặt hàng!",
	//Item
	15: "Mức độ ưu tiên này đã tồn tại!",
	33: "Không tìm thấy thông tin loại mặt hàng!",
	34: "Không tìm thấy thông tin mặt hàng!",
	104: "Không thể xoá sản phẩm, sản phẩm đang trong đơn hàng!",
	105: "Sản phẩm đã đi vào sản xuất, không thể chỉnh sửa sản phẩm!",
	//Order
	6: "Tên sản phẩm không được trống!",
	35: "Không tìm thấy thông tin đơn hàng!",
	36: "Template lỗi!",
	62: "Vui lòng thêm file báo giá để tạo đơn đặt hàng",
	63: "Vui lòng thêm sản phẩm vào file báo giá để tạo đơn đặt hàng!",
	64: "Không thể đọc file báo giá!",
	66: "Đơn vị không được trống!",
	67: "Đơn hàng không có sản phẩm không thể tạo file báo giá!",
	68: "Những mã sản phẩm không tìm thấy trong hệ thống:",
	69: "Ngày giờ bắt đầu phải lớn hơn hoặc bằng hiện tại!",
	74: "Vui lòng nhập ngày giờ bắt đầu trước khi thêm/sửa ngày kết thúc!",
	75: "Ngày giờ kết thúc phải lớn hơn ngày giờ bắt đầu!",
	//OrderDetail
	37: "Lỗi API 37: Tài khoản không đủ khả năng mở rộng",
	//LeaderTask
	14: "Không tìm thấy thông tin mặt hàng",
	38: "Không tìm thấy thông tin tổ trưởng!",
	39: "Không tìm thấy thông tin đơn hàng!",
	40: "Không tìm thấy thông tin quy trình!",
	41: "Công việc đã được tạo!",
	42: "Đơn hàng đang không tiến hành!",
	43: "Ngày bắt đầu không thể lớn hơn hoặc bằng ngày kết thúc!",
	44: "Không tìm thấy thông tin công việc tổ trưởng!",
	45: "Nhóm không hợp lệ!",
	46: "Nhóm đã xoá!",
	87: "Công việc nghiệm thu cho đơn hàng này đã được tạo!",
	91: "Mức độ ưu tiên này đã tồn tại!",
	103: "Mặt hàng chưa đủ 3 bản vẽ, hãy cập nhập đủ bản vẽ trong mặt hàng trước khi tạo công việc!",
	//WokerTask
	13: "Không tìm thấy thông tin báo cáo vấn đề!",
	47: "Không tìm thấy thông tin công việc công nhân!",
	48: "Công nhân đã được thêm vào công việc!",
	49: "Công nhân chưa được thêm vào công việc!",
	92: "Mức độ ưu tiên này đã tồn tại!",
	93: "Công nhân hiện đang làm công việc khác, không thể thêm vào công việc hiện tại!",
	107: "Không tìm thấy thông tin công việc công nhân chi tiết!",
	108: "Công việc này đã hoàn thành!",
	//TaskReport
	50: "Người dùng không phải tổ trưởng!",
	51: "Không tìm thấy thông tin công việc tổ trưởng!",
	52: "Báo cáo nghiệm thu cho công việc này đã được thực hiện!",
	53: "Đã qua ngày kết thúc công việc, không thể gửi báo cáo vào lúc này!",
	54: "Không tìm thấy thông tin báo cáo tiến độ!",
	55: "Báo cáo này đã hoàn thành!",
	111: "Báo cáo đã phản hồi không thể chỉnh sửa!",
	//OrderReport
	56: "Người dùng không phải quản đốc!",
	57: "Không tìm thấy thông tin đơn hàng!",
	58: "Đơn hàng đang không tiến hành!",
	59: "Báo cáo tiến độ cho đơn hàng này đã được thực hiện!",
	60: "Không tìm thấy thông tin báo cáo!",
	61: "Báo cáo này đã hoàn thành!",
	65: "Không tìm thấy thông tin quản đốc",
	100: "Đã quá hạn chỉnh sửa báo cáo!",
	//Procedure
	70: "Tên quy trình này đã tồn tại!",
	71: "Không tìm thấy thông tin quy trình!",
	77: "Quy trình này đang tồn tại trong sản phẩm, hãy xoá ra khỏi sản phẩm trước khi xoá quy trình!",
	//Step
	72: "Tên bước này đã tồn tại!",
	73: "Không tìm thấy thông tin bước!",
	76: "Bước này đang tồn tại trong quy trình, hãy xoá ra khỏi trước khi xoá bước!",
	//Report
	23: "Không tìm thấy thông tin công việc nghiệm thu!",
	86: "Chưa tới ngày bắt đầu công việc, không thể gửi báo cáo vào lúc này!",
	98: "Số lượng mặt hàng thất bại không lớn hơn số lượng mặt hàng!",
	101: "Đã quá hạn chỉnh sửa báo cáo!",
	//Notification
	88: "Không tìm thấy thông báo!",
	//Comment
	89: "Không tìm thấy thông tin công việc công nhân!",
	90: "Công việc đã hoàn thành, không thể gửi bình luận!",
	99: "Không tìm thấy thông tin bình luận!",
	//OrderDetail
	112: "Không tìm thấy thông tin đơn hàng!",
	113: "Không tìm thấy thông tin của sản phẩm!",
	109: "Sản phẩm đã tồn tại trong đơn hàng!",
	110: "Không tìm thấy thông tin vật liệu!",
	//Not used
};

export default ApiCodes;
