
const dataTaskMembers = [{
  id: 1,
  fullName: "Trần Quang Đạt"
}, {
  id: 2,
  fullName: "Phan Thanh Đức"
}, {
  id: 3,
  fullName: "Lê Tấn Phát"
},
]

export const mockTasks = [
  {
    id: "1",
    name: "Đơn 1",
    managerId: "1",
    managerName: "Manager 1",
    orderId: "1",
    orderName: "Order 1",
    procedureId: "1",
    description: "Đơn 1",
    team: "Team 1",
    timeStart: new Date("2022-01-01"),
    timeEnd: new Date("2022-10-01"),
    completedTime: new Date("2022-10-01"),
    productCompleted: 1,
    productFailed: 0,
    status: 1,
    isDeleted: false,
    members: dataTaskMembers,
  },
  {
    id: "2",
    name: "Đơn 2",
    managerId: "2",
    managerName: "Manager 2",
    orderId: "2",
    orderName: "Order 2",
    procedureId: "2",
    description: "Đơn 2",
    team: "Team 2",
    timeStart: new Date("2022-10-22"),
    timeEnd: new Date("2023-01-01"),
    completedTime: new Date("2023-01-01"),
    productCompleted: 1,
    productFailed: 0,
    status: 2,
    isDeleted: false,
    members: dataTaskMembers,
  },
  {
    id: "3",
    name: "Đơn 3",
    managerId: "3",
    managerName: "Manager 3",
    orderId: "3",
    orderName: "Order 3",
    procedureId: "3",
    description: "Đơn 3",
    team: "Team 3",
    timeStart: new Date("2023-04-01"),
    timeEnd: new Date("2023-05-01"),
    completedTime: new Date("2023-05-01"),
    productCompleted: 0,
    productFailed: 1,
    status: 3,
    isDeleted: false,
    members: dataTaskMembers,
  },
  {
    id: "4",
    name: "Đơn 4",
    managerId: "4",
    managerName: "Manager 4",
    orderId: "4",
    orderName: "Order 4",
    procedureId: "4",
    description: "Đơn 4",
    team: "Team 4",
    timeStart: new Date("2023-04-01"),
    timeEnd: new Date("2023-05-01"),
    completedTime: null,
    productCompleted: 0,
    productFailed: 1,
    status: 4,
    isDeleted: false,
    members: dataTaskMembers,
  },
  {
    id: "5",
    name: "Đơn 5",
    managerId: "5",
    managerName: "Manager 5",
    orderId: "5",
    orderName: "Order 5",
    procedureId: "5",
    description: "Đơn 5",
    team: "Team 5",
    timeStart: new Date("2023-04-01"),
    timeEnd: new Date("2023-05-01"),
    completedTime: null,
    productCompleted: 0,
    productFailed: 1,
    status: 5,
    isDeleted: false,
    members: dataTaskMembers,
  },
  {
    id: "6",
    name: "Đơn 6",
    managerId: "6",
    managerName: "Manager 6",
    orderId: "6",
    orderName: "Order 6",
    procedureId: "6",
    description: "Đơn 6",
    team: "Team 6",
    timeStart: new Date("2023-04-01"),
    timeEnd: new Date("2023-05-01"),
    completedTime: null,
    productCompleted: 0,
    productFailed: 1,
    status: 6,
    isDeleted: false,
    members: dataTaskMembers,
  },
  {
    id: "7",
    name: "Đơn 7",
    managerId: "7",
    managerName: "Manager 7",
    orderId: "7",
    orderName: "Order 7",
    procedureId: "7",
    description: "Đơn 7",
    team: "Team 7",
    timeStart: new Date("2023-04-01"),
    timeEnd: new Date("2023-05-01"),
    completedTime: null,
    productCompleted: 0,
    productFailed: 1,
    status: 7,
    isDeleted: false,
    members: dataTaskMembers,
  },
];


export const enumTaskStatuses = [
  {
    id: "0",
    enum: "Created",
    name: "Đã Tạo",
    color: "",
  },
  {
    id: "1",
    enum: "WaitingForActivation",
    name: "Chờ Kích Hoạt",
    color: "",
  },
  {
    id: "2",
    enum: "WaitingToRun",
    name: "Trong Hàng Đợi",
    color: "",
  },
  {
    id: "3",
    enum: "Running",
    name: "Đang Tiến Hành",
    color: "#cb7a00",
  },
  {
    id: "4",
    enum: "WaitingForChildrenToComplete",
    name: "Đang Chờ Công việc Khác",
    color: "",
  },
  {
    id: "5",
    enum: "RanToCompletion",
    name: "Đã Hoàn Thành",
    color: "#28cb00",
  },
  {
    id: "6",
    enum: "Canceled",
    name: "Đã Huỷ",
    color: "#cb050f",
  },
  {
    id: "7",
    enum: "Faulted",
    name: "Có Lỗi Xảy Ra",
    color: "",
  },
]